#pragma once
#include "IMap.h"

#define TILE_SIZE_X			8
#define TILE_SIZE_Y			8

enum class EMapTile_Type : uint16_t
{
	// 지나갈 수 있는 것들
	ROAD_STONE,
	ROAD_GRASS,
	ROAD_POKETMONCENTER,
	ROAD_CARPET_UP,
	ROAD_CARPET_DOWN,
	ROAD_SHOP,
	ROAD_GYM,
	POKETMON_GRASS,

	// 지나가고 트리거
	POKETMONCENTER_DOOR_LEFTUP,
	POKETMONCENTER_DOOR_RIGHTUP,
	POKETMONCENTER_DOOR_LEFTDOWN,
	POKETMONCENTER_DOOR_RIGHTDOWN,
	SHOP_DOOR_LEFTUP,
	SHOP_DOOR_RIGHTUP,
	SHOP_DOOR_LEFTDOWN,
	SHOP_DOOR_RIGHTDOWN,
	GYM_DOOR_LEFTUP,
	GYM_DOOR_RIGHTUP,
	GYM_DOOR_LEFTDOWN,
	GYM_DOOR_RIGHTDOWN,

	// 지나가지 못하는 것들
	TREE_LEFTUP,
	TREE_RIGHTUP,
	TREE_LEFTDOWN,
	TREE_RIGHTDOWN,
	BLANK,
	BUILDING_LEFTWALL,
	BUILDING_MIDDLEWALL,
	BUILDING_RIGHTWALL,
	BUILDING_LEFTDOWN,
	BUILDING_MIDDLEDOWN,
	BUILDING_RIGHTDOWN,
	POKET_SIGN_LEFT,
	POKET_SIGN_RIGHT,
	SHOP_SIGN_LEFT,
	SHOP_SIGN_RIGHT,
	SIGN_DOWN,
	GYM_SIGN_LEFT,
	GYM_SIGN_MIDDLE,
	GYM_SIGN_RIGHT,
	ROOF_LEFTUP,
	ROOF_MIDDLEUP,
	ROOF_RIGHTUP,
	ROOF_LEFTMIDDLE,
	ROOF_MIDDLEMIDDLE,
	ROOF_RIGHTMIDDLE,
	ROOF_LEFTDOWN,
	ROOF_MIDDLEDOWN,
	ROOF_RIGHTDOWN,
	WALL_POKETMONCENTER,
	HEALING_MACHINE_1_LEFT,
	HEALING_MACHINE_1_MIDDLE_LEFT,
	HEALING_MACHINE_1_MIDDLE_RIGHT,
	HEALING_MACHINE_1_RIGHT,
	HEALING_MACHINE_2_LEFT,
	HEALING_MACHINE_2_MIDDLE_LEFT,
	HEALING_MACHINE_2_MIDDLE_RIGHT,
	HEALING_MACHINE_2_RIGHT,
	HEALING_MACHINE_3_LEFT,
	HEALING_MACHINE_3_MIDDLE,
	HEALING_MACHINE_3_RIGHT,
	HEALING_MACHINE_4_LEFT,
	HEALING_MACHINE_4_MIDDLE_LEFT,
	HEALING_MACHINE_4_MIDDLE_RIGHT,
	HEALING_MACHINE_4_RIGHT,
	HEALING_MACHINE_5_LEFTUP,
	HEALING_MACHINE_5_RIGHTUP,
	HEALING_MACHINE_5_LEFTDOWN,
	HEALING_MACHINE_5_RIGHTDOWN,
	HEALING_MACHINE_6_LEFTUP,
	HEALING_MACHINE_6_RIGHTUP,
	HEALING_MACHINE_6_LEFTDOWN,
	HEALING_MACHINE_6_RIGHTDOWN,
	CENTER_TABLE_UP,
	CENTER_TABLE_DOWN,
	CENTER_TABLE_BELL,
	CENTER_TABLE_VERTICAL,
	SHOP_SOFA_1_LEFT,
	SHOP_SOFA_1_RIGHT,
	SHOP_SOFA_2_LEFT,
	SHOP_SOFA_2_RIGHT,
	SHOP_SOFA_3_LEFT,
	SHOP_SOFA_3_RIGHT,
	SHOP_SOFA_4_LEFT,
	SHOP_SOFA_4_RIGHT,
	SHOP_ICEBOX_1_LEFT,
	SHOP_ICEBOX_1_MIDDLE_LEFT,
	SHOP_ICEBOX_1_MIDDLE_RIGHT,
	SHOP_ICEBOX_1_RIGHT,
	SHOP_ICEBOX_2_LEFT,
	SHOP_ICEBOX_2_MIDDLE_LEFT,
	SHOP_ICEBOX_2_MIDDLE_RIGHT,
	SHOP_ICEBOX_2_RIGHT,
	SHOP_ICEBOX_3_LEFT,
	SHOP_ICEBOX_3_MIDDLE_LEFT,
	SHOP_ICEBOX_3_MIDDLE_RIGHT,
	SHOP_ICEBOX_3_RIGHT,
	SHOP_ICEBOX_4_LEFT,
	SHOP_ICEBOX_4_MIDDLE_LEFT,
	SHOP_ICEBOX_4_MIDDLE_RIGHT,
	SHOP_ICEBOX_4_RIGHT,
	SHOP_DRINGKING1_LEFT,
	SHOP_DRINGKING1_RIGHT,
	SHOP_DRINGKING2_LEFT,
	SHOP_DRINGKING2_RIGHT,
	SHOP_DRINGKING3_LEFT,
	SHOP_DRINGKING3_RIGHT,
	SHOP_DRINGKING4_LEFT,
	SHOP_DRINGKING4_RIGHT,
	SHOP_WALL,
	SHOP_TABLE_LEFTUP,
	SHOP_TABLE_RIGHTUP,
	SHOP_TABLE_LEFTMIDDLE,
	SHOP_TABLE_RIGHTMIDDLE,
	SHOP_TABLE_LEFT1DOWN,
	SHOP_TABLE_MIDDLE1DOWN,
	SHOP_TABLE_RIGHT1DOWN,
	SHOP_TABLE_LEFT2DOWN,
	SHOP_TABLE_MIDDLE2DOWN,
	SHOP_TABLE_RIGHT2DOWN,
	SHOP_COUNTER_LEFTUP,
	SHOP_COUNTER_RIGHTUP,
	SHOP_COUNTER_LEFTDOWN,
	SHOP_COUNTER_RIGHTDOWN,
	GYM_FALLROAD_UP,
	GYM_FALLROAD_DOWN,
	GYM_WALL,
	GYM_WALL2_LEFTUP,
	GYM_WALL2_RIGHTUP,
	GYM_WALL2_LEFTDOWN,
	GYM_WALL2_RIGHTDOWN,
	GYM_STATUE_LEFTUP,
	GYM_STATUE_RIGHTUP,
	GYM_STATUE_LEFTMIDDLE1,
	GYM_STATUE_RIGHTMIDDLE1,
	GYM_STATUE_LEFTMIDDLE2,
	GYM_STATUE_RIGHTMIDDLE2,
	GYM_STATUE_LEFTDOWN,
	GYM_STATUE_RIGHTDOWN
};

enum class EMap_Type : uint16_t
{
	VILLAGE,
	POKETMONCENTER,
	SHOP,
	GYM
};

class Map : public IMap
{
protected:
	char** m_chArrMap;
	EMapTile_Type** m_eMapTile_Type;
	EMap_Type m_MapType;

public:
	virtual void Init() PURE;

	char** GetMap() { return m_chArrMap; }
	EMapTile_Type** GetMapTile() { return m_eMapTile_Type; }
	EMap_Type GetMapType() { return m_MapType; }

	Map();
	virtual ~Map();
};